networks:
  default:
    driver: bridge

services:
  api:
    container_name: api
    extends:
      file: ./redmond/docker-compose.yml
      service: api
    volumes:
      - './redmond:/app'
    depends_on:
      - postgres
      - redis
      - zookeeper
      - broker
      - bank_1_api
  
  postgres:
    container_name: postgres
    extends:
      file: ./redmond/docker-compose.yml
      service: postgres

  redis:
    container_name: redis
    extends:
      file: ./redmond/docker-compose.yml
      service: redis
  
  zookeeper:
    container_name: zookeeper
    extends:
      file: ./redmond/docker-compose.yml
      service: zookeeper

  broker:
    container_name: broker
    extends:
      file: ./redmond/docker-compose.yml
      service: broker
    depends_on:
      - zookeeper
  
  bank_1_api:
    container_name: bank_1_api
    extends:
      file: ./bank/compose.yaml
      service: bank_1_api
    ports:
      - '8081:8080'
    volumes:
      - './bank:/app'
    depends_on:
      - bank_1_postgres
  
  bank_1_postgres:
    container_name: bank_1_postgres
    extends:
      file: ./bank/compose.yaml
      service: bank_1_postgres
      