services:  
  redmond-postgres:
    container_name: redmond-postgres
    extends:
      file: ./redmond/docker-compose-dev.yml
      service: redmond-postgres

  redmond-redis:
    container_name: redmond-redis
    extends:
      file: ./redmond/docker-compose-dev.yml
      service: redmond-redis
  
  redmond-zookeeper:
    container_name: redmond-zookeeper
    extends:
      file: ./redmond/docker-compose-dev.yml
      service: redmond-zookeeper

  redmond-broker:
    container_name: redmond-broker
    extends:
      file: ./redmond/docker-compose-dev.yml
      service: redmond-broker
    depends_on:
      - redmond-zookeeper
  
  bank-01:
    container_name: bank-01
    extends:
      file: ./bank/docker-compose.yaml
      service: bank-01
    ports:
      - '8081:80'
    depends_on:
      - bank-01-postgres
  
  bank-01-postgres:
    container_name: bank-01-postgres
    extends:
      file: ./bank/docker-compose.yaml
      service: bank-01-postgres

  redmond-mongo:
    container_name: redmond-mongo
    extends:
      file: ./redmond/docker-compose-dev.yml
      service: redmond-mongo
    ports:
      - "27017:27017"

  redmond-neo4j:
    container_name: redmond-neo4j
    extends:
      file: ./redmond/docker-compose.yml
      service: redmond-neo4j
    volumes:
      - ./redmond/data:/data
      - ./redmond/logs:/logs
