services:
  bank-01-api:
    container_name: bank-01-api
    build: .
    ports:
      - '8081:8080'
    depends_on:
      - bank-01-postgres
      
  bank-01-postgres:
    container_name: bank-01-postgres
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=bank1db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'

#  mongodb:
#    image: 'mongo:latest'
#    environment:
#      - 'MONGO_INITDB_DATABASE=bank2db'
#      - 'MONGO_INITDB_ROOT_PASSWORD=mongo'
#      - 'MONGO_INITDB_ROOT_USERNAME=mongo'
#    ports:
#      - '27017:27017'
